[2024-12-06T05:19:23.860+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T05:19:24.172+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2024-12-06T04:56:43.927065+00:00 [queued]>
[2024-12-06T05:19:24.191+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2024-12-06T04:56:43.927065+00:00 [queued]>
[2024-12-06T05:19:24.194+0000] {taskinstance.py:2866} INFO - Starting attempt 5 of 6
[2024-12-06T05:19:24.226+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_flow_table> on 2024-12-06 04:56:43.927065+00:00
[2024-12-06T05:19:24.242+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_flow_table', 'manual__2024-12-06T04:56:43.927065+00:00', '--job-id', '635', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphuv5pqps']
[2024-12-06T05:19:24.243+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2962) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T05:19:24.249+0000] {standard_task_runner.py:72} INFO - Started process 2976 to run task
[2024-12-06T05:19:24.248+0000] {standard_task_runner.py:105} INFO - Job 635: Subtask insert_into_flow_table
[2024-12-06T05:19:24.349+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2024-12-06T04:56:43.927065+00:00 [running]> on host 9ed27289a118
[2024-12-06T05:19:24.588+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_flow_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T04:56:43.927065+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T04:56:43.927065+00:00'
[2024-12-06T05:19:24.605+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T05:19:24.619+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T05:19:24.724+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_flow_table state:running start_date:2024-12-06 05:19:24.173590+00:00
[2024-12-06T05:19:24.728+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2024-12-06T05:19:24.731+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T05:19:24.732+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO Flow (FreeCashFlow,CapitalExpenditure,Year,Company)
            VALUES
                (74071000000.0,-44477000000.0,2021,'Microsoft'),
                (59475000000.0,-28107000000.0,2022,'Microsoft'),
                (65149000000.0,-23886000000.0,2023,'Microsoft'),
                (56118000000.0,-20622000000.0,2024,'Microsoft');
        
[2024-12-06T05:19:24.757+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-06T05:19:24.836+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-06T05:19:24.873+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO Flow (FreeCashFlow,CapitalExpenditure,Year,Company)
            VALUES
                (74071000000.0,-44477000000.0,2021,'Microsoft'),
                (59475000000.0,-28107000000.0,2022,'Microsoft'),
                (65149000000.0,-23886000000.0,2023,'Microsoft'),
                (56118000000.0,-20622000000.0,2024,'Microsoft');
        , parameters: None
[2024-12-06T05:19:24.886+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(4)

[2024-12-06T05:19:24.937+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T05:19:24.964+0000] {logging_mixin.py:190} INFO - Task start:2024-12-06 05:19:24.173590+00:00 end:2024-12-06 05:19:24.936652+00:00 duration:0.763062
[2024-12-06T05:19:24.980+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_flow_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2024-12-06 04:56:43.927065+00:00: manual__2024-12-06T04:56:43.927065+00:00, state:running, queued_at: 2024-12-06 04:56:44.175593+00:00. externally triggered: True>
[2024-12-06T05:19:24.995+0000] {logging_mixin.py:190} INFO - Failure caused by value too long for type character varying(4)
[2024-12-06T05:19:25.012+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_flow_table, run_id=manual__2024-12-06T04:56:43.927065+00:00, execution_date=20241206T045643, start_date=20241206T051924, end_date=20241206T051924
[2024-12-06T05:19:25.150+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T05:19:25.151+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 635 for task insert_into_flow_table (value too long for type character varying(4)
; 2976)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(4)

[2024-12-06T05:19:25.247+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T05:19:25.288+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
