[2025-01-08T01:57:29.363+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T01:57:29.418+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_curr_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T01:57:29.446+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_curr_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T01:57:29.450+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-08T01:57:29.524+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_curr_table> on 2025-01-08 01:57:22.741560+00:00
[2025-01-08T01:57:29.723+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_curr_table', 'manual__2025-01-08T01:57:22.741560+00:00', '--job-id', '700', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcvnprwox']
[2025-01-08T01:57:29.727+0000] {standard_task_runner.py:105} INFO - Job 700: Subtask insert_into_curr_table
[2025-01-08T01:57:29.740+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3419) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T01:57:29.768+0000] {standard_task_runner.py:72} INFO - Started process 3486 to run task
[2025-01-08T01:57:31.927+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_curr_table manual__2025-01-08T01:57:22.741560+00:00 [running]> on host ec6dd3d48f26
[2025-01-08T01:57:33.285+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_curr_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T01:57:22.741560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T01:57:22.741560+00:00'
[2025-01-08T01:57:33.385+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-08T01:57:33.389+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-08T01:57:33.396+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_curr_table state:running start_date:2025-01-08 01:57:29.422440+00:00
[2025-01-08T01:57:33.406+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2025-01-08T01:57:33.418+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T01:57:33.425+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO Curr (ShortTerm, Receivables, Inventory, HedgingAssetsCurrently, OtherCurrentAssets, Company)
            VALUES
                (47.3, 35.6, 0.8, 0.0075, 16.3, 'Microsoft'),
                (47.3, 35.6, 0.8, 0.0075, 16.3, 'Pepsico'),
                (47.3, 35.6, 0.8, 0.0075, 16.3, 'BlackRock');
        
[2025-01-08T01:57:33.638+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T01:57:33.816+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T01:57:33.878+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO Curr (ShortTerm, Receivables, Inventory, HedgingAssetsCurrently, OtherCurrentAssets, Company)
            VALUES
                (47.3, 35.6, 0.8, 0.0075, 16.3, 'Microsoft'),
                (47.3, 35.6, 0.8, 0.0075, 16.3, 'Pepsico'),
                (47.3, 35.6, 0.8, 0.0075, 16.3, 'BlackRock');
        , parameters: None
[2025-01-08T01:57:33.950+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "curr_pkey"
DETAIL:  Key (shortterm)=(47.3) already exists.

[2025-01-08T01:57:34.344+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-08T01:57:34.350+0000] {logging_mixin.py:190} INFO - Task start:2025-01-08 01:57:29.422440+00:00 end:2025-01-08 01:57:34.321692+00:00 duration:4.899252
[2025-01-08T01:57:34.354+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_curr_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2025-01-08 01:57:22.741560+00:00: manual__2025-01-08T01:57:22.741560+00:00, state:running, queued_at: 2025-01-08 01:57:22.791217+00:00. externally triggered: True>
[2025-01-08T01:57:34.355+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "curr_pkey"
DETAIL:  Key (shortterm)=(47.3) already exists.
[2025-01-08T01:57:34.356+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_curr_table, run_id=manual__2025-01-08T01:57:22.741560+00:00, execution_date=20250108T015722, start_date=20250108T015729, end_date=20250108T015734
[2025-01-08T01:57:34.781+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T01:57:34.785+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 700 for task insert_into_curr_table (duplicate key value violates unique constraint "curr_pkey"
DETAIL:  Key (shortterm)=(47.3) already exists.
; 3486)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "curr_pkey"
DETAIL:  Key (shortterm)=(47.3) already exists.

[2025-01-08T01:57:35.049+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T01:57:35.156+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
