[2025-01-08T02:07:42.446+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T02:07:42.486+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T02:07:42.511+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T02:07:42.513+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 6
[2025-01-08T02:07:42.558+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_flow_table> on 2025-01-08 01:57:22.741560+00:00
[2025-01-08T02:07:42.595+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9388) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T02:07:42.598+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_flow_table', 'manual__2025-01-08T01:57:22.741560+00:00', '--job-id', '726', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqerwn6m9']
[2025-01-08T02:07:42.602+0000] {standard_task_runner.py:72} INFO - Started process 9478 to run task
[2025-01-08T02:07:42.603+0000] {standard_task_runner.py:105} INFO - Job 726: Subtask insert_into_flow_table
[2025-01-08T02:07:42.752+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2025-01-08T01:57:22.741560+00:00 [running]> on host ec6dd3d48f26
[2025-01-08T02:07:43.049+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_flow_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T01:57:22.741560+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T01:57:22.741560+00:00'
[2025-01-08T02:07:43.059+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-08T02:07:43.060+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-08T02:07:43.064+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_flow_table state:running start_date:2025-01-08 02:07:42.487925+00:00
[2025-01-08T02:07:43.065+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2025-01-08T02:07:43.066+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T02:07:43.070+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO Flow (FreeCashFlow,CapitalExpenditure,Year,Company)
            VALUES
                (74071000000.0,-44477000000.0,2021,'Microsoft'),
                (59475000000.0,-28107000000.0,2022,'Microsoft'),
                (65149000000.0,-23886000000.0,2023,'Microsoft'),
                (56118000000.0,-20622000000.0,2024,'Microsoft'),

                (74071000000.0,-44477000000.0,2021,'Pepsico'),
                (59475000000.0,-28107000000.0,2022,'Pepsico'),
                (65149000000.0,-23886000000.0,2023,'Pepsico'),
                (56118000000.0,-20622000000.0,2024,'Pepsico'),

                (74071000000.0,-44477000000.0,2021,'BlackRock'),
                (59475000000.0,-28107000000.0,2022,'BlackRock'),
                (65149000000.0,-23886000000.0,2023,'BlackRock'),
                (56118000000.0,-20622000000.0,2024,'BlackRock');
        
[2025-01-08T02:07:43.096+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:07:43.133+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:07:43.149+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO Flow (FreeCashFlow,CapitalExpenditure,Year,Company)
            VALUES
                (74071000000.0,-44477000000.0,2021,'Microsoft'),
                (59475000000.0,-28107000000.0,2022,'Microsoft'),
                (65149000000.0,-23886000000.0,2023,'Microsoft'),
                (56118000000.0,-20622000000.0,2024,'Microsoft'),

                (74071000000.0,-44477000000.0,2021,'Pepsico'),
                (59475000000.0,-28107000000.0,2022,'Pepsico'),
                (65149000000.0,-23886000000.0,2023,'Pepsico'),
                (56118000000.0,-20622000000.0,2024,'Pepsico'),

                (74071000000.0,-44477000000.0,2021,'BlackRock'),
                (59475000000.0,-28107000000.0,2022,'BlackRock'),
                (65149000000.0,-23886000000.0,2023,'BlackRock'),
                (56118000000.0,-20622000000.0,2024,'BlackRock');
        , parameters: None
[2025-01-08T02:07:43.157+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(4)

[2025-01-08T02:07:43.218+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-08T02:07:43.220+0000] {logging_mixin.py:190} INFO - Task start:2025-01-08 02:07:42.487925+00:00 end:2025-01-08 02:07:43.217061+00:00 duration:0.729136
[2025-01-08T02:07:43.226+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_flow_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2025-01-08 01:57:22.741560+00:00: manual__2025-01-08T01:57:22.741560+00:00, state:running, queued_at: 2025-01-08 01:57:22.791217+00:00. externally triggered: True>
[2025-01-08T02:07:43.227+0000] {logging_mixin.py:190} INFO - Failure caused by value too long for type character varying(4)
[2025-01-08T02:07:43.229+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_flow_table, run_id=manual__2025-01-08T01:57:22.741560+00:00, execution_date=20250108T015722, start_date=20250108T020742, end_date=20250108T020743
[2025-01-08T02:07:43.286+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T02:07:43.290+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 726 for task insert_into_flow_table (value too long for type character varying(4)
; 9478)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(4)

[2025-01-08T02:07:43.352+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T02:07:43.416+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T02:07:43.419+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
