[2025-01-08T02:46:39.881+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T02:46:39.906+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_prices_table manual__2025-01-08T02:46:37.243913+00:00 [queued]>
[2025-01-08T02:46:39.919+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_prices_table manual__2025-01-08T02:46:37.243913+00:00 [queued]>
[2025-01-08T02:46:39.922+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-08T02:46:39.954+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_prices_table> on 2025-01-08 02:46:37.243913+00:00
[2025-01-08T02:46:39.972+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=32145) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T02:46:39.975+0000] {standard_task_runner.py:72} INFO - Started process 32192 to run task
[2025-01-08T02:46:39.983+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_prices_table', 'manual__2025-01-08T02:46:37.243913+00:00', '--job-id', '810', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg722vese']
[2025-01-08T02:46:39.996+0000] {standard_task_runner.py:105} INFO - Job 810: Subtask insert_into_prices_table
[2025-01-08T02:46:40.083+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_prices_table manual__2025-01-08T02:46:37.243913+00:00 [running]> on host ec6dd3d48f26
[2025-01-08T02:46:40.375+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_prices_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T02:46:37.243913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T02:46:37.243913+00:00'
[2025-01-08T02:46:40.380+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-08T02:46:40.381+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-08T02:46:40.382+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_prices_table state:running start_date:2025-01-08 02:46:39.908533+00:00
[2025-01-08T02:46:40.382+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2025-01-08T02:46:40.383+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T02:46:40.383+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO Pricees (Price, Year, Company)
            VALUES
               
                (71.061, 2014, 'Pepsico'),
                (74.952, 2015, 'Pepsico'),
                (81.53, 2016, 'Pepsico'),
                (91.399, 2017, 'Pepsico'),
                (92.251, 2018, 'Pepsico'),
                (110.09, 2019, 'Pepsico'),
                (120.637, 2020, 'Pepsico'),
                (137.18, 2021, 'Pepsico'),
                (160.91, 2022, 'Pepsico'),
                (170.46, 2023, 'Pepsico'),
                (168.93, 2024, 'Pepsico'),
                (272.33, 2014, 'BlackRock'),
                (281.99, 2015, 'BlackRock'),
                (349.96, 2016, 'BlackRock'),
                (415.73, 2017, 'BlackRock'),
                (389.42, 2018, 'BlackRock'),
                (499.60, 2019, 'BlackRock'),
                (773.49, 2020, 'BlackRock'),
                (643.11, 2021, 'BlackRock'),
                (666.24, 2022, 'BlackRock'),
                (856.88, 2023, 'BlackRock'),
                (1019.1, 2024, 'BlackRock');

        
[2025-01-08T02:46:40.427+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:46:40.486+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:46:40.506+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO Pricees (Price, Year, Company)
            VALUES
               
                (71.061, 2014, 'Pepsico'),
                (74.952, 2015, 'Pepsico'),
                (81.53, 2016, 'Pepsico'),
                (91.399, 2017, 'Pepsico'),
                (92.251, 2018, 'Pepsico'),
                (110.09, 2019, 'Pepsico'),
                (120.637, 2020, 'Pepsico'),
                (137.18, 2021, 'Pepsico'),
                (160.91, 2022, 'Pepsico'),
                (170.46, 2023, 'Pepsico'),
                (168.93, 2024, 'Pepsico'),
                (272.33, 2014, 'BlackRock'),
                (281.99, 2015, 'BlackRock'),
                (349.96, 2016, 'BlackRock'),
                (415.73, 2017, 'BlackRock'),
                (389.42, 2018, 'BlackRock'),
                (499.60, 2019, 'BlackRock'),
                (773.49, 2020, 'BlackRock'),
                (643.11, 2021, 'BlackRock'),
                (666.24, 2022, 'BlackRock'),
                (856.88, 2023, 'BlackRock'),
                (1019.1, 2024, 'BlackRock');

        , parameters: None
[2025-01-08T02:46:40.510+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pricees_pkey"
DETAIL:  Key (price)=(82) already exists.

[2025-01-08T02:46:40.535+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-08T02:46:40.543+0000] {logging_mixin.py:190} INFO - Task start:2025-01-08 02:46:39.908533+00:00 end:2025-01-08 02:46:40.534576+00:00 duration:0.626043
[2025-01-08T02:46:40.548+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_prices_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2025-01-08 02:46:37.243913+00:00: manual__2025-01-08T02:46:37.243913+00:00, state:running, queued_at: 2025-01-08 02:46:37.254149+00:00. externally triggered: True>
[2025-01-08T02:46:40.550+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "pricees_pkey"
DETAIL:  Key (price)=(82) already exists.
[2025-01-08T02:46:40.557+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_prices_table, run_id=manual__2025-01-08T02:46:37.243913+00:00, execution_date=20250108T024637, start_date=20250108T024639, end_date=20250108T024640
[2025-01-08T02:46:40.680+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T02:46:40.692+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 810 for task insert_into_prices_table (duplicate key value violates unique constraint "pricees_pkey"
DETAIL:  Key (price)=(82) already exists.
; 32192)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pricees_pkey"
DETAIL:  Key (price)=(82) already exists.

[2025-01-08T02:46:40.776+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T02:46:40.806+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
