[2025-01-08T02:02:38.325+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T02:02:38.357+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_noncurr_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T02:02:38.378+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_noncurr_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T02:02:38.381+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2025-01-08T02:02:38.414+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_noncurr_table> on 2025-01-08 01:57:22.741560+00:00
[2025-01-08T02:02:38.438+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_noncurr_table', 'manual__2025-01-08T01:57:22.741560+00:00', '--job-id', '718', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7fxf34gb']
[2025-01-08T02:02:38.440+0000] {standard_task_runner.py:105} INFO - Job 718: Subtask insert_into_noncurr_table
[2025-01-08T02:02:38.447+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6462) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T02:02:38.451+0000] {standard_task_runner.py:72} INFO - Started process 6498 to run task
[2025-01-08T02:02:38.531+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_noncurr_table manual__2025-01-08T01:57:22.741560+00:00 [running]> on host ec6dd3d48f26
[2025-01-08T02:02:38.780+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_noncurr_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T01:57:22.741560+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T01:57:22.741560+00:00'
[2025-01-08T02:02:38.784+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-08T02:02:38.796+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-08T02:02:38.807+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_noncurr_table state:running start_date:2025-01-08 02:02:38.358748+00:00
[2025-01-08T02:02:38.810+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2025-01-08T02:02:38.811+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T02:02:38.811+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO NonCurr (PPE, Intangibles, Investments, OtherNonCurrentAssets, Company)
            VALUES
                (43.9, 41.7, 4.1, 10.3, 'Microsoft'),
                (43.9, 41.7, 4.1, 10.3, 'Pepsico'),
                (43.9, 41.7, 4.1, 10.3, 'BlackRock');
        
[2025-01-08T02:02:38.837+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:02:38.855+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:02:38.864+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO NonCurr (PPE, Intangibles, Investments, OtherNonCurrentAssets, Company)
            VALUES
                (43.9, 41.7, 4.1, 10.3, 'Microsoft'),
                (43.9, 41.7, 4.1, 10.3, 'Pepsico'),
                (43.9, 41.7, 4.1, 10.3, 'BlackRock');
        , parameters: None
[2025-01-08T02:02:38.876+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.

[2025-01-08T02:02:38.912+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-08T02:02:38.914+0000] {logging_mixin.py:190} INFO - Task start:2025-01-08 02:02:38.358748+00:00 end:2025-01-08 02:02:38.911333+00:00 duration:0.552585
[2025-01-08T02:02:38.915+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_noncurr_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2025-01-08 01:57:22.741560+00:00: manual__2025-01-08T01:57:22.741560+00:00, state:running, queued_at: 2025-01-08 01:57:22.791217+00:00. externally triggered: True>
[2025-01-08T02:02:38.916+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.
[2025-01-08T02:02:38.917+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_noncurr_table, run_id=manual__2025-01-08T01:57:22.741560+00:00, execution_date=20250108T015722, start_date=20250108T020238, end_date=20250108T020238
[2025-01-08T02:02:38.949+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T02:02:38.950+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 718 for task insert_into_noncurr_table (duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.
; 6498)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.

[2025-01-08T02:02:38.979+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T02:02:39.061+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T02:02:39.064+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
