[2025-01-08T01:57:29.691+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T01:57:29.799+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_noncurr_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T01:57:29.841+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_noncurr_table manual__2025-01-08T01:57:22.741560+00:00 [queued]>
[2025-01-08T01:57:29.852+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-08T01:57:29.970+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_noncurr_table> on 2025-01-08 01:57:22.741560+00:00
[2025-01-08T01:57:30.310+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3425) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T01:57:30.536+0000] {standard_task_runner.py:72} INFO - Started process 3497 to run task
[2025-01-08T01:57:30.909+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_noncurr_table', 'manual__2025-01-08T01:57:22.741560+00:00', '--job-id', '704', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdaitjmlg']
[2025-01-08T01:57:30.995+0000] {standard_task_runner.py:105} INFO - Job 704: Subtask insert_into_noncurr_table
[2025-01-08T01:57:32.739+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_noncurr_table manual__2025-01-08T01:57:22.741560+00:00 [running]> on host ec6dd3d48f26
[2025-01-08T01:57:34.177+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_noncurr_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T01:57:22.741560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T01:57:22.741560+00:00'
[2025-01-08T01:57:34.191+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-08T01:57:34.198+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-08T01:57:34.204+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_noncurr_table state:running start_date:2025-01-08 01:57:29.800691+00:00
[2025-01-08T01:57:34.213+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2025-01-08T01:57:34.227+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T01:57:34.234+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO NonCurr (PPE, Intangibles, Investments, OtherNonCurrentAssets, Company)
            VALUES
                (43.9, 41.7, 4.1, 10.3, 'Microsoft'),
                (43.9, 41.7, 4.1, 10.3, 'Pepsico'),
                (43.9, 41.7, 4.1, 10.3, 'BlackRock');
        
[2025-01-08T01:57:34.566+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T01:57:34.802+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T01:57:34.843+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO NonCurr (PPE, Intangibles, Investments, OtherNonCurrentAssets, Company)
            VALUES
                (43.9, 41.7, 4.1, 10.3, 'Microsoft'),
                (43.9, 41.7, 4.1, 10.3, 'Pepsico'),
                (43.9, 41.7, 4.1, 10.3, 'BlackRock');
        , parameters: None
[2025-01-08T01:57:34.850+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.

[2025-01-08T01:57:34.952+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-08T01:57:34.959+0000] {logging_mixin.py:190} INFO - Task start:2025-01-08 01:57:29.800691+00:00 end:2025-01-08 01:57:34.949010+00:00 duration:5.148319
[2025-01-08T01:57:34.960+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_noncurr_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2025-01-08 01:57:22.741560+00:00: manual__2025-01-08T01:57:22.741560+00:00, state:running, queued_at: 2025-01-08 01:57:22.791217+00:00. externally triggered: True>
[2025-01-08T01:57:34.961+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.
[2025-01-08T01:57:34.962+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_noncurr_table, run_id=manual__2025-01-08T01:57:22.741560+00:00, execution_date=20250108T015722, start_date=20250108T015729, end_date=20250108T015734
[2025-01-08T01:57:35.067+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T01:57:35.072+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 704 for task insert_into_noncurr_table (duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.
; 3497)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "noncurr_pkey"
DETAIL:  Key (ppe)=(43.9) already exists.

[2025-01-08T01:57:35.181+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T01:57:35.308+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T01:57:35.349+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
