[2025-01-08T02:40:43.205+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T02:40:43.341+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2025-01-08T02:40:39.845385+00:00 [queued]>
[2025-01-08T02:40:43.373+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2025-01-08T02:40:39.845385+00:00 [queued]>
[2025-01-08T02:40:43.387+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-08T02:40:43.510+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_flow_table> on 2025-01-08 02:40:39.845385+00:00
[2025-01-08T02:40:43.671+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_flow_table', 'manual__2025-01-08T02:40:39.845385+00:00', '--job-id', '767', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxa01t66v']
[2025-01-08T02:40:43.673+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28540) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T02:40:43.690+0000] {standard_task_runner.py:72} INFO - Started process 28566 to run task
[2025-01-08T02:40:43.689+0000] {standard_task_runner.py:105} INFO - Job 767: Subtask insert_into_flow_table
[2025-01-08T02:40:44.370+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_flow_table manual__2025-01-08T02:40:39.845385+00:00 [running]> on host ec6dd3d48f26
[2025-01-08T02:40:44.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_flow_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T02:40:39.845385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T02:40:39.845385+00:00'
[2025-01-08T02:40:44.906+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-08T02:40:44.908+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-08T02:40:44.919+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_flow_table state:running start_date:2025-01-08 02:40:43.343020+00:00
[2025-01-08T02:40:44.920+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2025-01-08T02:40:44.920+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T02:40:44.921+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO Flow (FreeCashFlow,CapitalExpenditure,Year,Company)
            VALUES
                

                (7924000000.0, 1401000000.0, 'PepsiCo'),
                (5604000000.0, 1043000000.0, 'PepsiCo'),
                (6991000000.0, 1184000000.0, 'PepsiCo'),
                (6373000000.0, 1156000000.0, 'PepsiCo'),


                (3821000000.0, 200000000.0, 'BlackRock')
                (4423000000.0, 177000000.0, 'BlackRock')
                (4603000000.0, 189000000.0, 'BlackRock')
                (3549000000.0, 183000000.0, 'BlackRock');


        
[2025-01-08T02:40:44.936+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:40:44.948+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-08T02:40:44.959+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO Flow (FreeCashFlow,CapitalExpenditure,Year,Company)
            VALUES
                

                (7924000000.0, 1401000000.0, 'PepsiCo'),
                (5604000000.0, 1043000000.0, 'PepsiCo'),
                (6991000000.0, 1184000000.0, 'PepsiCo'),
                (6373000000.0, 1156000000.0, 'PepsiCo'),


                (3821000000.0, 200000000.0, 'BlackRock')
                (4423000000.0, 177000000.0, 'BlackRock')
                (4603000000.0, 189000000.0, 'BlackRock')
                (3549000000.0, 183000000.0, 'BlackRock');


        , parameters: None
[2025-01-08T02:40:44.969+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 13:                 (4423000000.0, 177000000.0, 'BlackRock')
                         ^

[2025-01-08T02:40:44.993+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-08T02:40:44.994+0000] {logging_mixin.py:190} INFO - Task start:2025-01-08 02:40:43.343020+00:00 end:2025-01-08 02:40:44.992752+00:00 duration:1.649732
[2025-01-08T02:40:44.996+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_flow_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2025-01-08 02:40:39.845385+00:00: manual__2025-01-08T02:40:39.845385+00:00, state:running, queued_at: 2025-01-08 02:40:39.939975+00:00. externally triggered: True>
[2025-01-08T02:40:44.996+0000] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "("
LINE 13:                 (4423000000.0, 177000000.0, 'BlackRock')
                         ^
[2025-01-08T02:40:44.998+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_flow_table, run_id=manual__2025-01-08T02:40:39.845385+00:00, execution_date=20250108T024039, start_date=20250108T024043, end_date=20250108T024044
[2025-01-08T02:40:45.023+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T02:40:45.027+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 767 for task insert_into_flow_table (syntax error at or near "("
LINE 13:                 (4423000000.0, 177000000.0, 'BlackRock')
                         ^
; 28566)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 13:                 (4423000000.0, 177000000.0, 'BlackRock')
                         ^

[2025-01-08T02:40:45.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T02:40:45.082+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
